stages:
  - build
  - deploy

build-springboot:
  stage: build
   - source 
   -
  only:
    -main
  tags:
    -quality

deploy-springboot
  stage: deploy
  script:
    - source
  only:
    - main
  tags:
    - quality