stages:
  - build
  - deploy

build-springboot:
  stage: build
  script:
    - source profile.d
    - mvn clean package
  only:
    - main
  tags:
    - quality

deploy-springboot:
  stage: deploy
  script:
    - source profile.d
    - zsh run.sh 
  only:
    - main
  tags:
    - quality