stages:
  - build
  - deploy

build-springboot:
  stage: build
  script:
    - source /etc/profile
  only:
    - main
  tags:
    - quality

deploy-springboot:
  stage: deploy
  script:
    - source /etc/profile 
    - zsh run.sh 
  only:
    - main
  tags:
    - quality