stages:
  - build
  - deploy

build-springboot:
  stage: build
  only:
    -main
  tags:
    -quality

deploy-springboot:
  stage: deploy
  script:
    - ps -ef | grep api.py | awk '{print $2}' | xargs kill -9
    - nohup java -jar .mvn/wrapper/maven-wrapper.jar > /home/peng/springboot.log 2>&1 &
  only:
    - main
  tags:
    - quality