stages:
  - build
  - deploy

build-springboot:
  stage: build
  script:
    - source java-env
  only:
    - v0.2
  tags:
    - quality

deploy-springboot:
  stage: deploy
  script:
    - source java-env
    - zsh run.sh 
  only:
    - main
    - v0.2
  tags:
    - quality