stages:
  - build
  - deploy

build-springboot:
  stage: build
  script:
    - source /usr/local/maven/apache-maven-3.9.4/bin/mvn
    - mvn clean package
  only:
    - main
  tags:
    - quality

deploy-springboot:
  stage: deploy
  script:
    - source /usr/local/maven/apache-maven-3.9.4/bin/mvn
    - ps -ef | grep api.py | awk '{print $2}' | xargs kill -9
    - nohup java -jar springboot1-0.0.1-SNAPSHOT.jar > /home/peng/springboot.log 2>&1 &
  only:
    - main
  tags:
    - quality