server:
  ip: localhost
  port: 9091

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/peng?serverTimezone=GMT%2b8
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB  #最大文件 100M
      max-request-size: 10MB

mybatis:
  mapper-locations:
      classpath: mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false

logging:
  config: classpath:logback-spring.xml

serverInfo:
  # baseurl项目部署后的访问地址
  baseurl: http://172.20.138.208:9090/
    #uploadpath为上传文件的保存路径
  uploadpath: /home/images
#  uploadpath: E:\project\IDEA\project\system

python:
  #python端的接口地址
  url: http://172.20.138.208:5000/api/mmdetection/predict
